name: Build iperf3 x64 static via cygwin64
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install cygwin tools
        run: .\cygwin-installer.cmd

      - name: Build static
        run: |
          ./system\bin\bash.exe -lc 'git clone "https://github.com/esnet/iperf.git" "$HOME/iperf3_build"'
          ./system\bin\bash.exe -lc 'cd "$HOME/iperf3_build"; ./bootstrap.sh'
          ./system\bin\bash.exe -lc 'cd "$HOME/iperf3_build"; ./configure --disable-shared --enable-static-bin --prefix=$HOME/iperf3'
          ./system\bin\bash.exe -lc 'cd "$HOME/iperf3_build"; make'
          ./system\bin\bash.exe -lc 'cd "$HOME/iperf3_build"; make install'

      - name: Archive build
        run: Compress-Archive .\home\iperf3 iperf3-amd64-win.zip

      - name: "Create release"
        uses: ncipollo/release-action@v1
        with:
          prerelease: false
          artifacts: "iperf3-amd64-win.zip"
          replacesArtifacts: true
          tag: test
          name: Iperf3
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
