name: Build iperf3 x64 static via cygwin action
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - run: git config --global core.autocrlf input

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Cygwin
        uses: cygwin/cygwin-install-action@master
        with:
          platform: x86_64
          packages: automake,gcc-core,gcc-g++,git,libtool,make

      - name: pwd
        run: |
          echo "Running in $(pwd)"
        shell: C:\cygwin\bin\bash.exe '{0}'

      - name: Build script
        run: C:\cygwin\bin\bash.exe build.sh

      - name: Archive build
        run: Compress-Archive iperf3 iperf3-amd64-win.zip

      - name: "Create release"
        uses: ncipollo/release-action@v1
        with:
          prerelease: false
          artifacts: "iperf3-amd64-win.zip"
          replacesArtifacts: true
          tag: test
          name: Iperf3
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
