name: Build iperf3 x64 static via cygwin64
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - run: git config --global core.autocrlf input

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install cygwin tools
        run: .\cygwin-installer.cmd

      - name: Build static
        run: |
          .\system\bin\bash.exe -l build.sh

      - name: Archive build
        run: Compress-Archive iperf3 iperf3-amd64-win.zip

      - name: "Create release"
        uses: ncipollo/release-action@v1
        with:
          prerelease: false
          artifacts: "iperf3-amd64-win.zip"
          replacesArtifacts: true
          tag: test_1
          name: Iperf3
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
